[package]
name = "fegrid-iec60870-cs101"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories = ["no-std", "network-programming"]
description = "IEC 60870-5-101 FT 1.2 link layer codec"

[lints]
workspace = true

[features]
default = ["std"]
std = []

[dependencies]
fegrid-iec60870-core = { workspace = true }
fegrid-iec60870-asdu = { workspace = true }
winnow = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }